<?php

/**
 * @file
 * Essex Restricted Content hooks.
 */

/**
 * Implements hook_entity_view_mode_alter().
 */
function ecc_restricted_content_entity_view_mode_alter(&$view_mode, $entity, $context) {
  if ($entity->getEntityTypeId() === 'node' && $entity->bundle() === 'localgov_news_article') {
    if (\Drupal::currentUser()->isAnonymous()) {
      $view_mode = match ($view_mode) {
        'full' => 'full_anonymous',
        default => 'teaser_anonymous'
      };
    }
  }
}