stages:
  - build
  - development
  - development-postdeploy
  - preproduction
  - preproduction-postdeploy
  - production
  - production-postdeploy

build-and-push-images:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_PASS: ""
  before_script:
    - apk add py3-pip gcc musl-dev python3-dev libffi-dev openssl openssl-dev cargo make
    - pip install --upgrade pip
    - pip install azure-cli
    - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
    - docker login -u${DOCKER_USER} -p${DOCKER_PASSWORD} ${DOCKER_REGISTRY}
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build -t ${DOCKER_REGISTRY}/intranet-drupal-fpm${tag} -t intranet-drupal-fpm -f Dockerfile-drupal .
    - docker build -t ${DOCKER_REGISTRY}/intranet-nginx-drupal${tag} -t intranet-nginx-drupal -f Dockerfile-nginx .
    - docker push ${DOCKER_REGISTRY}/intranet-nginx-drupal${tag}
    - docker push ${DOCKER_REGISTRY}/intranet-drupal-fpm${tag}
  only:
    - develop
    - /^release\//

deploy-to-dev:
  image: mcr.microsoft.com/azure-cli
  stage: development
  needs: ["build-and-push-images"]
  environment:
    name: development
    url: https://essex-gov-pp.nomensa.xyz/
  before_script:
    - az extension add --name containerapp
    - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - echo "Creating new revision of Container App"
    - | 
      cat > revision.yml <<EOF
      properties:
        template:
          revisionSuffix: ${CI_PIPELINE_ID}
          containers:
            - image: acreccuksdev.azurecr.io/intranet-nginx-drupal$tag
              name: nginx
              resources:
                cpu: 0.25
                memory: 0.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol      
            - image: acreccuksdev.azurecr.io/intranet-drupal-fpm$tag
              name: drupal
              resources:
                cpu: 0.75
                memory: 1.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
              - mountPath: /drupal/data/default/private
                volumeName: privsharevol
              env:
              - name: MYSQL_HOST
                value: mariadb-ecc-uks-dev.mariadb.database.azure.com
              - name: MYSQL_USER
                value: mariadb-root
              - name: MYSQL_DATABASE
                value: drupal_intranet
              - name: MYSQL_PASSWORD
                secretRef: mysql-password
      EOF
    - az containerapp revision copy --name intranet --resource-group rg-ecc-intranet-uks-dev --yaml revision.yml --subscription "Essex County Council (intranet)"
  rules:
    - when: manual

# drush-deploy-dev:
#   image: mcr.microsoft.com/azure-cli
#   stage: development-postdeploy
#   needs: ["deploy-to-dev"]
#   before_script:
#     - az extension add --name containerapp
#     - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
#   script:
#     - az containerapp exec --command /drupal/deploy.sh --name intranet --container drupal --resource-group rg-ecc-intranet-uks-dev --subscription "Essex County Council (intranet)"
#   rules:
#     - when: manual

deploy-to-preprod:
  image: mcr.microsoft.com/azure-cli
  stage: preproduction
  needs: ["deploy-to-dev"]
  environment:
    name: preproduction
    url: https://essex-gov-pp.nomensa.xyz/
  before_script:
    - az extension add --name containerapp
    - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
  script:    
    - echo "Importing image from Development  into Pre-Production"
    - az acr import --name acreccukspre --source acreccuksdev.azurecr.io/intranet-nginx-drupal:${CI_COMMIT_REF_SLUG} --image intranet-nginx-drupal:${CI_COMMIT_REF_SLUG} --subscription "Essex County Council (Common)"
    - | 
      cat > revision.yml <<EOF
      properties:
        template:
          revisionSuffix: ${CI_PIPELINE_ID}
          containers:
            - image: acreccukspre.azurecr.io/intranet-nginx-drupal:${CI_COMMIT_REF_SLUG}
              name: nginx
              resources:
                cpu: 0.25
                memory: 0.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
            - image: acreccukspre.azurecr.io/intranet-drupal-fpm:${CI_COMMIT_REF_SLUG}
              name: drupal
              resources:
                cpu: 0.75
                memory: 1.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
              env:
              - name: MYSQL_HOST
                value: mariadb-ecc-uks-pre.mariadb.database.azure.com
              - name: MYSQL_USER
                value: mariadb-root
              - name: MYSQL_DATABASE
                value: drupal_intranet
              - name: MYSQL_PASSWORD
                secretRef: mysql-password
      EOF
    - echo "Creating new revision of Container App"
    - az containerapp revision copy --name intranet --resource-group rg-ecc-intranet-uks-pre --yaml revision.yml --subscription "Essex County Council (intranet)"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\//
      when: manual

# drush-deploy-preprod:
#   image: mcr.microsoft.com/azure-cli
#   stage: preproduction-postdeploy
#   needs: ["deploy-to-preprod"]
#   before_script:
#     - az extension add --name containerapp
#     - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
#   script:
#     - az containerapp exec --command /drupal/deploy.sh --name intranet --container drupal --resource-group rg-ecc-intranet-uks-pre --subscription "Essex County Council (intranet)"
#   rules:
#     - if: $CI_COMMIT_BRANCH =~ /^release\//
#       when: manual

deploy-to-prod:
  image: mcr.microsoft.com/azure-cli
  stage: production
  needs: ["deploy-to-dev"]
  environment:
    name: production
    url: https://essex.gov.uk/
  before_script:
    - az extension add --name containerapp
    - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
  script:
    - echo "Importing image from Pre-Production into Production"
    - az acr import --name acreccuksprod --source acreccukspre.azurecr.io/intranet-nginx-drupal:${CI_COMMIT_REF_SLUG} --image intranet-nginx-drupal:${CI_COMMIT_REF_SLUG} --subscription "Essex County Council (Common)"
    - echo "Creating new revision of Container App"
    - | 
      cat > revision.yml <<EOF
      properties:
        template:
          revisionSuffix: ${CI_PIPELINE_ID}
          containers:
            - image: acreccuksprod.azurecr.io/intranet-nginx-drupal:${CI_COMMIT_REF_SLUG}
              name: nginx
              resources:
                cpu: 0.25
                memory: 0.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
            - image: acreccuksprod.azurecr.io/intranet-drupal-fpm:${CI_COMMIT_REF_SLUG}
              name: drupal
              resources:
                cpu: 0.75
                memory: 1.5Gi
              volumeMounts:
              - mountPath: /drupal/web/sites/default/files
                volumeName: filesharevol
              - mountPath: /drupal/data/default/private
                volumeName: privsharevol
              env:
              - name: MYSQL_HOST
                value: mariadb-ecc-uks-prod.mariadb.database.azure.com
              - name: MYSQL_USER
                value: mariadb-root
              - name: MYSQL_DATABASE
                value: drupal_intranet
              - name: MYSQL_PASSWORD
                secretRef: mysql-password
      EOF
    - az containerapp revision copy --name intranet --resource-group rg-ecc-intranet-uks-prod --yaml revision.yml --subscription "Essex County Council (intranet)"  
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^release\//
      when: manual

# drush-deploy-prod:
#   image: mcr.microsoft.com/azure-cli
#   stage: production-postdeploy
#   needs: ["deploy-to-prod"]
#   before_script:
#     - az extension add --name containerapp
#     - az login --service-principal -u${ARM_CLIENT_ID} -p${ARM_CLIENT_SECRET} -t${ARM_TENANT_ID}
#   script:
#     - az containerapp exec --command /drupal/deploy.sh --name intranet --container drupal --resource-group rg-ecc-intranet-uks-prod --subscription "Essex County Council (intranet)"
#   rules:
#     - if: '$CI_COMMIT_BRANCH =~ /^release\//
#       when: manual
