version: '3.8'
services:
  nginx-drupal:
    depends_on:
      - drupal-fpm
    hostname: nginx-drupal
    container_name: nginx-drupal
    image: "ecccontainerregistry.azurecr.io/nginx-drupal:latest"
    restart: unless-stopped
    ports:
      - "443:443"
  
  drupal-fpm:
    image: "ecccontainerregistry.azurecr.io/drupal-fpm:latest"
    restart: unless-stopped
    hostname: drupal-fpm
    container_name: drupal-fpm
    environment:
      MYSQL_HOST: "mariadb-ecc-dev-svr.mariadb.database.azure.com"
      MYSQL_USER: "mariadb-root"
      MYSQL_PASSWORD: "UbrwX+3H%B[N%g}UoR9+)y(c"
      MYSQL_DATABASE: "drupal"


  







