FROM debian:bullseye-slim as drupal-build

# For php8.1
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install \
    curl \
    wget \
    lsb-release

RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list && apt-get update
# Install needed packages
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive \
  && apt-get -y install \
  git \
  unzip \
  sudo \
  procps \
  php8.1-apcu \
  php8.1-uploadprogress \
  php8.1-fpm \
  php8.1-xml \
  php8.1-mbstring \
  php8.1-mysqli \
  php8.1-pgsql \
  php8.1-gd \
  php8.1-curl \
  php8.1-zip \
  default-mysql-client \
  libmemcached11 \
  libmemcachedutil2 \
  libmemcached-dev \
  php-pear \
  php-dev \
  gnupg2 \
  zlib1g-dev \
  apt-transport-https \
  ca-certificates \
  software-properties-common \
  libxml2-dev \
  libcurl4-openssl-dev \
  libmagickwand-dev \
  libonig-dev \
  libzip-dev \
  rsync \
  libwebp-dev \
  libjpeg62-turbo-dev \
  libpng-dev \
  libxpm-dev \
  libfreetype6-dev \
  && apt-get clean all

RUN update-alternatives --set php /usr/bin/php8.1

#RUN git clone https://github.com/Imagick/imagick.git --depth 1 /tmp/imagick
    #&& \
#    cd /tmp/imagick && \
#    git fetch origin pull/641/head:fix-unterminated-preprocessor-conditions && \
#    git switch fix-unterminated-preprocessor-conditions

#RUN cd /tmp/imagick && \
#    phpize && \
#    ./configure && \
#    make && \
#    make install

#ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

#RUN chmod +x /usr/local/bin/install-php-extensions && \
#    install-php-extensions imagick

RUN pecl channel-update pecl.php.net \
    && pecl download imagick \
    && ls \
    #&& tar xzf imagick-3.7.0.tgz \
    #&& patch mypatch.diff imagick/Imagick.stub.php \
    #&& tar czf imagick-3.7.0-patch01.tgz imagick package.xml \
    #&& pecl install ./imagick-3.7.0.tgz
    && pecl install imagick memcached

# Download and install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Download and install security checker
ENV PHP_CHECKER_VERSION=1.0.0
RUN curl -o /tmp/security_checker -L "https://github.com/fabpot/local-php-security-checker/releases/download/v${PHP_CHECKER_VERSION}/local-php-security-checker_${PHP_CHECKER_VERSION}_linux_amd64" \
    && mv /tmp/security_checker /usr/bin/local-php-security-checker \
    && chmod +x /usr/bin/local-php-security-checker

# create volume for shared SSH keys
RUN mkdir -p /drupal/data/default/ssh-keys
VOLUME ["/drupal/data/default/ssh-keys"]



# create Drupal folders
RUN mkdir -p /drupal/web/sites/default/files \
  && mkdir -p /drupal/data/default/private \
  && mkdir -p /drupal/data/default/temp \
  && mkdir -p /drupal/config/default \
  && usermod -d /drupal www-data \
  && chown -hR www-data:www-data /drupal

RUN update-rc.d php8.1-fpm disable

COPY --chown=www-data:www-data ./ /drupal

COPY scripts/. /scripts

WORKDIR /drupal

RUN sed -i 's;listen = /run/php/php8.1-fpm.sock;listen = 9000;' /etc/php/8.1/fpm/pool.d/www.conf
RUN echo "clear_env = no" >> /etc/php/8.1/fpm/pool.d/www.conf
RUN echo 'extension="memcached.so"' >> /etc/php/8.1/fpm/conf.d/20-memcached.ini
RUN sed -i 's;expose_php = on;expose_php = off;' /etc/php/8.1/fpm/php.ini && mkdir -p /run/php
RUN sed -i 's;memory_limit = 128M;memory_limit = 512M;' /etc/php/8.1/fpm/php.ini
RUN sed -i 's;upload_max_filesize = 2M;upload_max_filesize = 128M;' /etc/php/8.1/fpm/php.ini
RUN sed -i 's;post_max_size = 8M;post_max_size = 128M;' /etc/php/8.1/fpm/php.ini

RUN export HOME=/tmp \
  && sudo -E -u www-data composer install

RUN ln -s /drupal/vendor/drush/drush/drush /usr/bin/drush \
  && chmod 755 /drupal/deploy.sh

EXPOSE 80

CMD php-fpm8.1 -F -R
