settings:
  type: config_object
  label: "Restricted Content settings"
  mapping:
    restricted_content_types:
      type: sequence
      label: 'Content types'
      sequence:
        - type: string
