<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function ecc_auth_preprocess_page(&$variables) {
  $config = \Drupal::config('ecc_auth.settings');
  $require_header = $config->get('require_header') ?: FALSE;
  if ($require_header) {
    $header_key = $config->get('header_key');
    $expected_header_value = $config->get('expected_header_value');
    if ($header_key && $expected_header_value) {
      $actual_header_value = \Drupal::request()->headers->get($header_key);
      \Drupal::logger('mine')->debug('header: ' . $actual_header_value);
    }
    if (empty($actual_header_value) || $actual_header_value !== $expected_header_value) {
      return;
    }
  }
  $account = \Drupal::currentUser();
  if (\Drupal::routeMatch()->getRouteName() === 'ecc_auth.popunder_loggedin') {
    if ($account->isAuthenticated()) {
      $variables['#attached']['library'][] = 'ecc_auth/popunder_loggedin';
    }
    return;
  }
  if ($account->isAnonymous()) {
    $variables['#attached']['library'][] = 'ecc_auth/popunder';
  }
}