<?php

use Drupal\user\UserInterface;

/**
 * Implements hook_preprocess_HOOK().
 */
function ecc_auth_preprocess_page(&$variables) {
  switch (\Drupal::routeMatch()->getRouteName()) {
    case 'entity.node.canonical':
      if (\Drupal::currentUser()->isAnonymous()) {
        $variables['#attached']['library'][] = 'ecc_auth/auto_login';
      }
      break;

    case 'ecc_auth.auto_login_logged_in':
      if (\Drupal::currentUser()->isAuthenticated()) {
        $variables['#attached']['library'][] = 'ecc_auth/auto_login_logged_in';
      }
  }
}

/**
 * Implements hook_user_login().
 *
 * Set a cookie showing the user has logged in from the Essex network.
 */
function ecc_auth_user_login(UserInterface $account) {
  $config = \Drupal::config('ecc_auth.settings');
  if ($config->get('require_header')) {
    $header_key = $config->get('header_key');
    $expected_header_value = $config->get('expected_header_value');
    if ($header_key && $expected_header_value) {
      $actual_header_value = \Drupal::request()->headers->get($header_key);
    }
    if (empty($actual_header_value) || $actual_header_value !== $expected_header_value) {
      return;
    }
  }
  setcookie('essex-user', 'true', time() + 31536000, '/');
}