ecc_auth.settings:
  type: config_object
  label: "Essex Auth settings"
  mapping:
    enabled:
      type: boolean
      label: "Enabled"
    require_header:
      type: boolean
      label: "Require header"
    header_key:
      type: string
      label: "Header key"
    expected_header_value:
      type: string
      label: "Expected header value"
