ecc_auth.settings:
  type: config_object
  label: "Essex Auth settings"
  mapping:
    enabled:
      type: boolean
      label: "Enabled"
    client:
      type: string
      label: "OpenID Connect client id"
