gull_cookie_settings_block:
  js:
    js/gull_cookie_settings.js: {}
  dependencies:
    - eu_cookie_compliance/eu_cookie_compliance_bare
    - eu_cookie_compliance/eu_cookie_compliance

# @see eu_cookie_compiance.settings.disabled_javascripts Drupal config.
deferred-scripts:
  js:
    js/deferred-hotjar-script-runner.js: {}
    js/deferred-ga-script.js-runner: {}
  dependencies:
    - core/drupalSettings
