#!/usr/bin/env bash

## #ddev-generated
## Description: Run backstop
## Usage: backstop-host
## Example: ddev backstop-host

ddev backstop --config=tests/backstop/backstop.config.js test
backstop --config=tests/backstop/backstop.config.js openReport
