oidc_auto_login.settings:
  type: config_object
  label: "OpenID Connect Auto-login settings"
  mapping:
    enabled:
      type: boolean
      label: "Enabled"
    client:
      type: string
      label: "OpenID Connect client id"
    header_required:
      type: boolean
      label: "Require header"
    header_key:
      type: string
      label: "Header key"
    header_value:
      type: string
      label: "Expected header value"
