<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\cache\CachePluginBase;
use \Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * @file
 * Primary module hooks for ECC Comment module.
 */

/**
 * Implements hook_theme_suggestions_HOOK_alter() for comments.
 */
function ecc_comment_theme_suggestions_comment_alter(array &$suggestions, array $variables) {
  // Add a new template suggestion for the comment.
  $suggestions[] = 'comment__ecc_comment';
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for comments.
 */
function ecc_comment_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  if ($variables['element']['#field_type'] === 'comment') {
    // Add a new template suggestion for the comment field.
    $suggestions[] = 'field__ecc_comment';
  }
}

/**
 * Implements hook_theme().
 */
function ecc_comment_theme($existing, $type, $theme, $path) {
  return [
    'comment__ecc_comment' => [
      'template' => 'ecc-comment',
      'base hook' => 'comment',
    ],
    'field__ecc_comment' => [
      'template' => 'field--ecc-comment',
      'base hook' => 'field',
    ],
  ];
}

/**
 * Implements template_preprocess_comment();
 */
function ecc_comment_preprocess_comment(&$variables) {
  // Check if the 'submitted' variable exists and is a TranslatableMarkup object.
  if (isset($variables['submitted']) && $variables['submitted'] instanceof \Drupal\Core\StringTranslation\TranslatableMarkup) {
    // Convert the TranslatableMarkup object to a string.
    $submitted_string = $variables['submitted']->render();

    // Remove the "Submitted by " part from the string.
    $submitted_string = str_replace('Submitted by ', '', $submitted_string);

/**
 * Implements hook_views_post_render()
 *
 * Adds custom styles to the view.
 */
function ecc_comment_views_post_render(ViewExecutable $view, array &$output, CachePluginBase $cache) {
  if ($view->id() == 'new_comments_for_review') {
    $output['#attached']['library'][] = 'ecc_comment/ecc-comment';
  }
}
