/**
* DO NOT EDIT THIS FILE.
* See the following change record for more information,
* https://www.drupal.org/node/2815083
* @preserve
**/

(function setupCookieSettingsBlock($, Drupal) {
  Drupal.behaviors.activateCookieSettingsForm = {
    attach: function attach(context) {
      var selectedCookieCategories = Drupal.eu_cookie_compliance.getAcceptedCategories();

      Drupal.eu_cookie_compliance.setAcceptedCategories(selectedCookieCategories);
      Drupal.eu_cookie_compliance.loadCategoryScripts(selectedCookieCategories);

      Drupal.eu_cookie_compliance.setPreferenceCheckboxes(selectedCookieCategories);
      Drupal.eu_cookie_compliance.attachSavePreferencesEvents();

      $("#eu-cookie-compliance-categories", context).once().each(displayCheckboxAsRadios);
    }
  };

  function displayCheckboxAsRadios() {
    setTimeout(function () {
      hideCheckboxes();
      clickRadiosBasedOnCheckboxStatus();
      setupUpClickHandlersForRadios();
      setupSaveSettingsFeedback();
    }, 300);
  }

  function hideCheckboxes() {
    $("[name=cookie-categories]:checkbox").hide();
  }

  function clickRadiosBasedOnCheckboxStatus() {
    $("[name=cookie-categories]:checked + .eu-cookie-compliance-categories--on :radio:not(:checked)").prop("checked", true);
    $("[name=cookie-categories]:not(:checked) + .eu-cookie-compliance-categories--on + .eu-cookie-compliance-categories--off :radio:not(:checked)").prop("checked", true);
  }

  function setupUpClickHandlersForRadios() {
    $(".eu-cookie-compliance-categories--on :radio, .eu-cookie-compliance-categories--off :radio").click(function (event) {
      var key = event.target.value;
      var relatedCheckboxId = "cookie-category-" + key;

      $("#" + relatedCheckboxId).click();
    });
  }

  function setupSaveSettingsFeedback() {

    var toneButton = document.querySelector('.eu-cookie-compliance-save-preferences-button');

    toneButton.addEventListener("click", function () {
      toneButton.innerHTML = "Saving";
      toneButton.classList.add('spinning');

      setTimeout(
        function () {
          toneButton.classList.remove('spinning');
          toneButton.innerHTML = "Preferences Saved <i class='fas fa-check'></i>";
        }, 2000);

    }, false);

    toneButton.addEventListener("blur", function () {
      toneButton.innerHTML = "Save Preferences  <i class='fas fa-check'></i>";
    }, false);

  }

})(jQuery, Drupal);