<?php

/**
 * @file
 * Essex Restricted Content hooks.
 */

use Drupal\node\NodeForm;

/**
 * Implements hook_entity_view_mode_alter().
 */
function localgov_restricted_content_entity_view_mode_alter(&$view_mode, $entity, $context) {
  if (\Drupal::currentUser()->isAnonymous()) {
    if (\Drupal::service('localgov_restricted_content.restricted_content')
      ->isRestricted($entity)) {
      $view_mode = match ($view_mode) {
        'full' => 'full_anonymous',
        'teaser' => 'teaser_anonymous',
        default => $view_mode
      };
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function localgov_restricted_content_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  /** @var \Drupal\node\NodeForm $node_form */
  $node_form = $form_state->getBuildInfo()['callback_object'];
  if (!($node_form instanceof NodeForm)) {
    return;
  }

  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  $entity = $node_form->getEntity();

  if (\Drupal::service('localgov_restricted_content.restricted_content')->isAncestorRestricted($entity)) {
    $form['localgov_restricted_content']['#suffix'] = t('<div class="form-item__label option">This is disabled because the page\'s parent is restricted.</div>');
    $form['localgov_restricted_content']['#disabled'] = TRUE;
    $form['localgov_restricted_content']['widget']['value']['#default_value'] = TRUE;
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function localgov_restricted_content_entity_extra_field_info() {
  $return = [];
  foreach (['localgov_news_article'] as $bundle) {
    $return['node'][$bundle]['display']['restricted_content_sign_in'] = [
      'label' => t('Sign in link'),
      'description' => t('Display sign in link at the bottom'),
      'visible' => TRUE,
    ];
    $return['node'][$bundle]['display']['restricted_content_sign_in_with_message'] = [
      'label' => t('Sign in link with message'),
      'description' => t('Display sign in link with message at the bottom'),
      'visible' => TRUE,
    ];
  }

  return $return;
}

/**
 * Implements hook_entity_view().
 */
function localgov_restricted_content_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  $content = $display->get('content');
  if (isset($content['restricted_content_sign_in_with_message'])) {
    $build['sign_in'] = [
      '#theme' => 'localgov_restricted_content_sign_in_with_message',
    ];
  }
  elseif (isset($content['restricted_content_sign_in'])) {
    $build['sign_in'] = [
      '#theme' => 'localgov_restricted_content_sign_in',
    ];
  }
}

/**
 * Implements hook_theme().
 */
function localgov_restricted_content_theme($existing, $type, $theme, $path) {
  return [
    'localgov_restricted_content_sign_in' => [
      'render element' => 'elements',
      ],
    'localgov_restricted_content_sign_in_with_message' => [
      'render element' => 'elements',
    ],
  ];
}