<?php

/**
 * @file
 * Essex Restricted Content hooks.
 */

/**
 * Implements hook_entity_view_mode_alter().
 */
function localgov_restricted_content_entity_view_mode_alter(&$view_mode, $entity, $context) {
  if (\Drupal::service('localgov_restricted_content.restricted_content')->isRestricted($entity)) {
    $view_mode = match ($view_mode) {
      'card' => 'card_anonymous',
      'full' => 'full_anonymous',
      'search_index' => 'search_index_anonymous',
      'search_result' => 'search_result_anonymous',
      default => 'teaser_anonymous'
    };
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function localgov_restricted_content_preprocess_node(&$variables) {
  $variables['restricted_content_message'] = t('This page is restricted, please sign in to see the full page.');

}