<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function oidc_auto_login_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'oidc_auto_login/login';
  switch (\Drupal::routeMatch()->getRouteName()) {
    case 'entity.node.canonical':
      if (\Drupal::currentUser()->isAnonymous()) {
        $variables['#attached']['library'][] = 'oidc_auto_login/login';
      }
      break;

  }
}
