name: Start reviewapp when PR is opened

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  start_reviewapp:
    name: Start reviewapp
    runs-on: ubuntu-latest
    steps:
      - name: Add comment for start of job
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Starting reviewapp

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ vars.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ vars.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ vars.ARM_TENANT_ID }}"}'

      - name: Deploy review app
        id: deploy
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          REF_NAME: ${{ github.head_ref }}
        shell: bash
        run: |
          CI_COMMIT_BRANCH="$REF_NAME"
          ENV_SLUG=$(echo "${REF_NAME}" | sed -e 's:[^[:alpha:]|^[:digit:]]:-:g' | sed -e 's/\(.*\)/\L\1/')
          NEW_DB_SUFFIX = "intranet_${ENV_SLUG}"
          tag=":$ENV_SLUG"
          az extension add --name containerapp --allow-preview true
          az containerapp job start -n intranet-dbclone -g rg-ecc-intranet-uks-dev --subscription "Essex County Council (Intranet)" --image "acreccuksdev.azurecr.io/dbclone" --env-vars "NEW_DB_SUFFIX=${NEW_DB_SUFFIX}" 'MYSQL_HOST=mariadb-ecc-uks-dev.mariadb.database.azure.com' 'MYSQL_USER=mariadb-root' 'MYSQL_DATABASE=drupal_intranet' 'MYSQL_PASSWORD=secretref:mysql-password' --container-name dbclonea --cpu 0.75 --memory 1.5
          echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
          sleep 4m
          jq -n --argjson revisions $(az containerapp revision list -n intranet -g rg-ecc-intranet-uks-dev --subscription "Essex County Council (Intranet)" | jq -c '[.[].name]') --argjson ingress $(az containerapp ingress show -n intranet -g rg-ecc-intranet-uks-dev --subscription "Essex County Council (Intranet)"  | jq -c ".traffic | [.[].revisionName]") '{"revisions": $revisions, "ingress": $ingress} | .revisions-.ingress | .[]' | tr -d '"' | while read revision
          do
            echo Deactivating "$revision"
            az containerapp revision deactivate --revision $revision -g rg-ecc-intranet-uks-dev --subscription "Essex County Council (Intranet)"
          done
          echo "Creating new revision of Container App"
          cat > revision.yml <<EOF
          properties:
            template:
              revisionSuffix: gh${GITHUB_RUN_ID}
              scale:
                minReplicas: 0
                maxReplicas: 1
                rules:
                  - name: "http-rule"
                    http:
                      metadata:
                        concurrentRequests: 40
              containers:
                - image: acreccuksdev.azurecr.io/intranet-nginx-drupal$tag
                  name: nginx
                  resources:
                    cpu: 0.25
                    memory: 0.5Gi
                  volumeMounts:
                  - mountPath: /drupal/web/sites/default/files
                    volumeName: filesharevol
                  env:
                  - name: X_ROBOTS_TAG
                    value: noindex
                  probes:
                  - type: liveness
                    httpGet:
                      path: "/dd822309-ae33-4e29-addf-869b07453a06"
                      port: 80
                    initialDelaySeconds: 5
                    periodSeconds: 3
                - image: acreccuksdev.azurecr.io/intranet-drupal-fpm$tag
                  name: drupal
                  resources:
                    cpu: 0.75
                    memory: 1.5Gi
                  volumeMounts:
                  - mountPath: /drupal/web/sites/default/files
                    volumeName: filesharevol
                  - mountPath: /drupal/data/default/private
                    volumeName: privsharevol
                  env:
                  - name: MYSQL_HOST
                    value: mariadb-ecc-uks-dev.mariadb.database.azure.com
                  - name: MYSQL_USER
                    value: mariadb-root
                  - name: MYSQL_DATABASE
                    value: drupal_ci_${NEW_DB_SUFFIX}
                  - name: MYSQL_PASSWORD
                    secretRef: mysql-password
                  - name: OPENID_CONNECT_PARAMS
                    secretRef: openid-connect-params
                  - name: NOMENSA_AAD_CLIENT_SECRET
                    secretRef: nomensa-aad-client-secret
                  - name: CLIENT_AAD_CLIENT_SECRET
                    secretRef: client-aad-client-secret
                  - name: ENVIRONMENT
                    value: dev
                  - name: FATHOM_ID
                    value: ''
                  probes:
                  - type: liveness
                    tcpSocket:
                      port: 9000
                    initialDelaySeconds: 5
                    periodSeconds: 3
          EOF
          az containerapp revision copy -n intranet -g rg-ecc-intranet-uks-dev --yaml revision.yml --subscription "Essex County Council (Intranet)" | tee revision.json 
          az containerapp revision label add --no-prompt -g rg-ecc-intranet-uks-dev -n intranet --label ${ENV_SLUG} --revision intranet--gh${GITHUB_RUN_ID} --subscription "Essex County Council (Intranet)"
          echo "env_slug=${ENV_SLUG}" >> "$GITHUB_OUTPUT"

      - name: Drush deploy
        id: drush_deploy
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          REF_NAME: ${{ github.head_ref }}
        shell: bash
        run: |
          CI_COMMIT_BRANCH="$REF_NAME"
          ENV_SLUG=$(echo "${REF_NAME}" | sed -e 's:[^[:alpha:]|^[:digit:]]:-:g' | sed -e 's/\(.*\)/\L\1/')
          tag=":$ENV_SLUG"
          echo Drush deploy started
          sudo apt-get -qq update
          sudo apt-get -y install socat
          timeout 1200 socat EXEC:"az containerapp exec --command /drupal/deploy.sh -n intranet --container drupal --revision intranet--gh${GITHUB_RUN_ID} -g rg-ecc-intranet-uks-dev --subscription \'Essex County Council (Intranet)\'",pty,setsid,ctty STDIO,ignoreeof
          echo Drush deploy finished

      - name: Add comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Started reviewapp
            https://intranet---${{ steps.deploy.outputs.env_slug }}.braveplant-96d7f42a.uksouth.azurecontainerapps.io/
